# Basic workflow for installing the package and running tests.

name: CI

on:
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.6, 3.7, 3.8 ]
        tensorflow-version: [ 2.0, 2.1, 2.2, 2.3, 2.4, 2.5 ]
        # No Pip packages for TF <2.2 and python 3.8:
        exclude:
          - { python-version: 3.8, tensorflow-version: 2.0}
          - { python-version: 3.8, tensorflow-version: 2.1}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies (TF version ${{ matrix.tensorflow-version }})
        run: |
          python -m pip install --upgrade pip
          python -m pip install tensorflow==${{matrix.tensorflow-version}}
          pip install .
      - name: Run tests
        run: make test

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - name: lint code
        run: |
          pip install pre-commit~=2.12
          make lint
